### ISSUE TITLE
Template string variables in JSX raises "Unexpected token ILLEGAL"

### ISSUE THREAD

**Issue by BenoitZugmeyer** [eslint/espree#95] opened 2015-03-14 20:39 UTC
This is a regression from espree 0.12.0.

```js
var espree = require('espree');

espree.parse('<foo bar={`${baz}`} />', {
    ecmaFeatures: {
        templateStrings: true,
        jsx: true
    }
});
// Raises: Unexpected token ILLEGAL
```

The same code without `${baz}` is OK

**Comment by nzakas** [comment] 2015-03-14 21:03
Must have to do with the template string changes.

Just so we're clear, you're saying this is a regression from v1.11.0 that you found in v1.12.0?

**Comment by BenoitZugmeyer** [comment] 2015-03-14 21:14
Oh, yes it is (I mixed up version numbers)

**Comment by lencioni** [comment] 2015-03-16 00:12
Sometimes I also see messages like:

```
182  -1  error  Unexpected quasi
     myProp={
```

In cases where I am using ES6 template strings in props as well.

**Comment by mikesherov** [comment] 2015-03-16 13:53
@nzakas let me know what you find. My guess is missing curlyStack pop push inside JSX expressions.

**Comment by nzakas** [comment] 2015-03-19 02:52
Related: https://github.com/jquery/esprima/pull/1145

**Comment by mikesherov** [comment] 2015-03-19 14:49
@lencioni 

```
182  -1  error  Unexpected quasi
     myProp={
```

Can you provide an actual code snippet that exhibits this bug?

**Comment by kentor** [comment] 2015-03-19 16:30
Hey I'm having this problem as well, and it's breaking my CI build :)

This will reproduce the `Unexpected quasi` error:

```javascript
<a>{`${1}`}{``}</a>
```

```
  1:11  error  Unexpected quasi {
```

**Comment by mikesherov** [comment] 2015-03-19 16:47
@nzakas you should be able to take my patch and see if it fixes @kentor 's issue.

**Comment by nzakas** [comment] 2015-03-19 19:18
Yup. Since we have `lookahead2()`, I'm anticipating that will do it. Just don't have the time to dig in yet.

**Comment by lencioni** [comment] 2015-03-19 21:19
@mikesherov here's a simplified repro case:

```jsx
const React = require('react/addons');

const MyComponent = React.createClass({
  render: function() {
    return (
      <div>
        <div myProp={`${this.props.something}`}/>
        <div differentProp={`${this.props.anotherThing}`}/>
      </div>
    );
  }
});

module.exports = MyComponent;
```

**Comment by mikesherov** [comment] 2015-03-19 23:13
jquery/esprima#1145 has landed with some additional perf improvements.

**Comment by nzakas** [comment] 2015-03-21 17:18
Working on this.

**Comment by nzakas** [comment] 2015-03-21 17:56
@mikesherov Yup, these fixes fixed all the issues mentioned in this issue.

**Closed** 2015-03-21 18:24 UTC
Labels: accepted, bug

**Comment by eprouty** [comment] 2015-05-27 17:10
I just ran `npm install eslint@latest` and have a .eslintrc that has this in it.

```json
ecmaFeatures": {
    "templateStrings": true,
    "jsx": true
}
```

But when linting a `.jsx` file that has the follow line in it `<form action='/round', method='POST',role='form'>` I get this output...

```bash
  8:34  error  Unexpected token ,

✖ 1 problem (1 error, 0 warnings)
```

Am I missing something needed to get your fixes working @nzakas?

**Comment by xjamundx** [comment] 2015-05-27 17:14
I'm not super sharp, but isn't that invalid code?

```
<form action='/round', method='POST',role='form'>
```

I got a similar error when putting this through the babel (jsx-compatible) repl:
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&playground=false&code=%3Cform%20action%3D'%2Fround'%2C%20method%3D'POST'%2Crole%3D'form'%3E

**Comment by eprouty** [comment] 2015-05-27 17:19
Hah, you are correct, that actually was an unexpected token... there shouldn't a `,` there.  Silly mistake on my part.

Also means this linter is working correctly and I was being obstinate!  Thanks, and nice work.

**Comment by Rastalamm** [comment] 2015-11-14 01:20
Is this fixed? 

I am getting a Parsing Error: unexpected token ILLEGAL on the $

```
`${apiHost}/users/${user.id}/cart`
```

**Comment by nzakas** [comment] 2015-11-14 16:48
The issue is still open, so it's not fixed yet.

**Comment by ilyavolodin** [comment] 2015-11-14 16:54
@nzakas This issue is actually closed. It looks like the fix didn't catch all of the cases, or @Rastalamm is using an older version without the fix.

**Comment by mikesherov** [comment] 2015-11-14 17:03
@rastalamm, what version are you using? And what is the complete JS you're trying to parse?

**Comment by Rastalamm** [comment] 2015-11-14 17:03
@ilyavolodin - I thought the issue was closed! 

I ran npm install -g eslint & npm install -g eslint@latest and using version 2.14.7

**Comment by Rastalamm** [comment] 2015-11-14 17:04
@mikesherov 

```
function getUserCart(req, ignore, next) {
        var user = req.user;
        request.get(`${apiHost}/carts?user_id=${user.id}`, {json: true}, function (err, httpResponse, cart) {
            if (httpResponse.statusCode === 200) {
                req.cart = cart.CartItems;
            }
            next();
        });
    }
```

**Comment by Rastalamm** [comment] 2015-11-14 17:06
So you guys can actually ignore this!! I am posting on the wrong thread! (Its been a long week)

I was having the issue with the npm package eslint and just noticed this is for espree.. 

Sorry about that!

**Comment by mikesherov** [comment] 2015-11-14 17:07
You'll wind up back here though. Eslint uses espree

**Comment by mikesherov** [comment] 2015-11-14 17:07
I'll see if this is a bug in latest Esprima. @nzakas I suggest you check this in acorn if you're switching soon anyway.
