### ISSUE TITLE
espree.tokenize doesnt tokenize comments

### ISSUE THREAD

**Issue by ChrisMGeo** [eslint/espree#411] opened 2019-02-25 10:10 UTC
I'm trying to create a syntax highlighting tool and am using espree which is fantastic, as it's easy to use in just 4 lines. However I don't know if this is due to my lack of research or just bad knowledge in JS, however the espree.tokenize function doesn't return comments in the following code:
```
const espree = require("espree");
var tokenized = espree.tokenize("var i = 0;\nfunction sayName(name){\n\tconsole.log('Hi '+ name)\n}\n//omg this is a comment\nconst espree=require('espree')", {comment:false});
console.log(tokenized);
```
Is there a way where I can show the comments as well and could I remove any token ignorance.

**Comment by ChrisMGeo** [comment] 2019-02-25 10:11
I have also tried comment: true; as well but I don't even know if that is related to this or not.

**Comment by nzakas** [comment] 2019-03-07 01:56
This is working as intended. Comments are not returned as tokens (this mimics the behavior of Esprima's `tokenize()` method). If you specify `comments: true`, then there is an extra `comments` array on the returned value:

```js
const tokens = espree.tokenize(code, { comments: true });
tokens.comments.forEach(/* whatever */);
```

You can then use the locations of the tokens and comments to merge them into one array if you'd like.

**Comment by kaicataldo** [comment] 2019-04-22 16:38
Closing this issue as it looks like the question has been answered. Please feel free to visit us in the [ESLint Gitter](https://gitter.im/eslint/eslint) if you have any other issues!

**Closed by kaicataldo** 2019-04-22 16:38 UTC
Labels: question
