### ISSUE TITLE
`Keyword` tokens output as `Identifier`

### ISSUE THREAD

**Issue by bradzacher** [eslint/espree#428] opened 2020-01-21 21:18 UTC
Running this small example through astexplorer
```js
async function *foo() {        // async === Identifier ################
                               // function === Keyword
  var a;                       // var === Keyword
  let b;                       // let === Keyword
  const c = {                  // const === Keyword
    get d() {},                // get === Identifier ################
    set e(val) {},             // set === Identifier ################
  }
  await f;                     // await === Identifier ################
  yield g;                     // yield === Keyword
  typeof x;                    // typeof === Keyword
  a in x;                      // in === Keyword
}

class H {                      // class === Keyword
  static i() {}                // static === Keyword
}

if (true) {} else {}           // if === Keyword
                               // else === Keyword 
try {} catch {} finally {}     // try === Keyword
                               // catch === Keyword
                               // finally === Keyword
for (;;) {}                    // for === Keyword
do { } while (true);           // do === Keyword
                               // while === Keyword
for (let x of y) {}            // for === Keyword
                               // of === Identifier ################
```
[repl](https://astexplorer.net/#/gist/64a872691c918f615302c6f6735ff84e/9229e8f142352a7aba92132bc44a22535bb640cb)

It looks like there are a few keywords which are incorrectly parsed as identifiers instead of keywords. I found:
- `async`
- `await`
- `get`
- `set`
- `of`

**Comment by kaicataldo** [comment] 2020-01-22 22:31
Thanks for reporting this. This does look like a bug to me, though I think it will need to be fixed upstream in Acorn.

**Comment by bradzacher** [comment] 2020-01-22 23:10
Sure! I didn't actually realise espree was built on top of acorn until today!
https://github.com/acornjs/acorn/issues/902

**Comment by ilyavolodin** [comment] 2020-01-23 15:37
Looks like acorn issue was close as "working as intended" so, unfortunately, since espree wouldn't have any more context then acorn does, I think we would have to close this issue as well. Thanks for creating it, though.

**Closed by ilyavolodin** 2020-01-23 15:37 UTC
Labels: blocked, bug, evaluating
